#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/iflv

get_config() {
	config_get_bool enabled $1 enabled 0
	config_get work_mode $1 work_mode 'dual_line'
	config_get iptv_provider $1 iptv_provider 'china_telecom'
	config_get iptv_region $1 iptv_region 'shanghai'
}

get_interface() {
	config_get modem_port $1 modem_port
	config_get stb_port $1 stb_port
	config_get vlan_id $1 vlan_id
	config_get inner_vlan_id $1 inner_vlan_id
}

get_system() {
	config_get log_level $1 log_level 'info'
	config_get_bool auto_start $1 auto_start 1
	config_get_bool auto_analyze $1 auto_analyze 1
}

start_service() {
	config_load iflv
	config_foreach get_config globals
	config_foreach get_interface interface
	config_foreach get_system system
	
	[ "$enabled" = "0" ] && return 1
	
	procd_open_instance
	procd_set_param command $PROG
	procd_append_param command --work-mode "$work_mode"
	procd_append_param command --modem-port "$modem_port"
	procd_append_param command --stb-port "$stb_port"
	
	if [ "$work_mode" = "vlan" ] || [ "$work_mode" = "vlan_passthrough" ]; then
		procd_append_param command --vlan-id "$vlan_id"
	fi
	
	if [ "$work_mode" = "vlan_passthrough" ]; then
		procd_append_param command --inner-vlan-id "$inner_vlan_id"
	fi
	
	procd_append_param command --provider "$iptv_provider"
	procd_append_param command --region "$iptv_region"
	procd_append_param command --log-level "$log_level"
	
	[ "$auto_analyze" = "1" ] && procd_append_param command --auto-analyze
	
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "iflv"
}

reload_service() {
	stop
	start
} 